-- MySQL Script generated by MySQL Workbench
-- Sun Mar 19 12:43:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `default_schema` ;

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `default_schema` ;
-- -----------------------------------------------------
-- Schema zmsite
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `zmsite` ;

-- -----------------------------------------------------
-- Schema zmsite
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zmsite` DEFAULT CHARACTER SET utf8 ;
USE `default_schema` ;

-- -----------------------------------------------------
-- Table `tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `zmsite` ;

-- -----------------------------------------------------
-- Table `empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empleado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(300) NOT NULL,
  `apellidos` VARCHAR(300) NOT NULL,
  `puesto` VARCHAR(300) NOT NULL,
  `email` VARCHAR(300) NOT NULL,
  `empresa` VARCHAR(300) NOT NULL,
  `creation_date` DATETIME NOT NULL,
  UNIQUE INDEX (`email` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(300) NOT NULL,
  `password` VARCHAR(300) NOT NULL,
  `rol` INT NOT NULL,
  UNIQUE INDEX (`email` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regis_bita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regis_bita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idEmpleado` INT NOT NULL,
  `nombre` VARCHAR(300) NOT NULL,
  `apellidos` VARCHAR(300) NOT NULL,
  `puesto` VARCHAR(300) NOT NULL,
  `empresa` VARCHAR(300) NOT NULL,
  `motivo` VARCHAR(300) NOT NULL,
  `hora_entra` DATETIME NOT NULL,
  `hora_sali` DATETIME NOT NULL,
  `IsExcited` BOOLEAN NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
